version: '3.5'
services:
  adonis:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./:/app
    # links:
    #   - nginx:nginx
    ports:
      - "8080:3000"
  # nginx:
  #   build: ./nginx/
  #   ports:
  #     - 80:80
  #     - 443:443
  #   expose:
  #     - 80
  #     - 443
