export const GET_ORDERS = 'GET_ORDERS'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_STATUSES = 'GET_ORDER_STATUSES'
export const SET_STATUS = 'SET_STATUS'
